pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
               script {
                  sh '''#!/bin/bash -xe
                     printenv
                     echo "====> ${CHANGE_TARGET} ${BRANCH_NAME}"
                     if [ \"x${BRANCH_NAME}\" != \"x${CHANGE_TARGET}\" ] ; then
                        for iter in `git log --format="%H" \
                        origin/"${BRANCH_NAME}"...origin/"${CHANGE_TARGET}"` ; do
                           if ! git show $iter | grep "^+" | codespell - ; then
                              echo "Codespell failed on commit $iter"
                              exit 1
                           fi
                           git show --stat $iter > checkpatch_input.txt
                           git show $iter >> checkpatch_input.txt
                           if cat checkpatch_input.txt | \
                           ./scripts/checkpatch.pl \
                           --strict \
		           --ignore=NO_AUTHOR_SIGN_OFF \
                           --ignore=BAD_SIGN_OFF - ; then
                              echo "INFO:checkpatch.pl succeeded"
                           else
                              echo "ERROR:checkpatch.pl failed on commit $iter"
                              exit 1
                           fi
                        done
                     fi
                     source /opt/alif/apss-tiny/yocto_5.0/0.1/environment-setup-cortexa32hf-neon-poky-linux-musleabi
                     git checkout ${BRANCH_NAME}

                     make distclean
                     make -j64 devkit_e8_defconfig
                     make -j64 xipImage
                     make alif/ensemble/devkit/devkit-e8.dtb

                  '''
               }
            }
        }
    }
}

